"""empty message

Revision ID: 132f9830e1e4
Revises: None
Create Date: 2016-06-25 00:39:55.033597

"""

# revision identifiers, used by Alembic.
revision = '132f9830e1e4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=40), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_age', 'users', ['age'], unique=True)
    op.create_index('ix_users_code', 'users', ['code'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_sex', 'users', ['sex'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('religionSurveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_religionSurveys_timestamp', 'religionSurveys', ['timestamp'], unique=False)
    op.create_table('postSurveys_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helpful_b', sa.String(length=20), nullable=True),
    sa.Column('useful_b', sa.String(length=20), nullable=True),
    sa.Column('curious_b', sa.String(length=20), nullable=True),
    sa.Column('satisfy_b', sa.String(length=20), nullable=True),
    sa.Column('annoy_b', sa.String(length=20), nullable=True),
    sa.Column('frustrated_b', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_postSurveys_b_timestamp', 'postSurveys_b', ['timestamp'], unique=False)
    op.create_table('postSurveys_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helpful_a', sa.String(length=20), nullable=True),
    sa.Column('useful_a', sa.String(length=20), nullable=True),
    sa.Column('curious_a', sa.String(length=20), nullable=True),
    sa.Column('satisfy_a', sa.String(length=20), nullable=True),
    sa.Column('annoy_a', sa.String(length=20), nullable=True),
    sa.Column('frustrated_a', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_postSurveys_a_timestamp', 'postSurveys_a', ['timestamp'], unique=False)
    op.create_table('preSurveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_preSurveys_timestamp', 'preSurveys', ['timestamp'], unique=False)
    op.create_table('brainSurveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brainSurveys_timestamp', 'brainSurveys', ['timestamp'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summaries_timestamp', 'summaries', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_summaries_timestamp', 'summaries')
    op.drop_table('summaries')
    op.drop_index('ix_brainSurveys_timestamp', 'brainSurveys')
    op.drop_table('brainSurveys')
    op.drop_index('ix_preSurveys_timestamp', 'preSurveys')
    op.drop_table('preSurveys')
    op.drop_index('ix_postSurveys_a_timestamp', 'postSurveys_a')
    op.drop_table('postSurveys_a')
    op.drop_index('ix_postSurveys_b_timestamp', 'postSurveys_b')
    op.drop_table('postSurveys_b')
    op.drop_index('ix_religionSurveys_timestamp', 'religionSurveys')
    op.drop_table('religionSurveys')
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_sex', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_index('ix_users_code', 'users')
    op.drop_index('ix_users_age', 'users')
    op.drop_table('users')
    op.drop_index('ix_roles_default', 'roles')
    op.drop_table('roles')
    ### end Alembic commands ###
