"""empty message

Revision ID: 2f597f4ba38e
Revises: 4821b527fd0c
Create Date: 2016-06-28 19:04:40.070178

"""

# revision identifiers, used by Alembic.
revision = '2f597f4ba38e'
down_revision = '4821b527fd0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
