"""empty message

Revision ID: 4821b527fd0c
Revises: 39aaa3530412
Create Date: 2016-06-28 17:40:08.360650

"""

# revision identifiers, used by Alembic.
revision = '4821b527fd0c'
down_revision = '39aaa3530412'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
