"""additional data registration

Revision ID: 5dbf76972a4f
Revises: 4ed5491aa522
Create Date: 2016-05-10 17:25:53.200207

"""

# revision identifiers, used by Alembic.
revision = '5dbf76972a4f'
down_revision = '4ed5491aa522'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('code', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=True)
    op.create_index(op.f('ix_users_code'), 'users', ['code'], unique=True)
    op.create_index(op.f('ix_users_sex'), 'users', ['sex'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sex'), table_name='users')
    op.drop_index(op.f('ix_users_code'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'code')
    op.drop_column('users', 'age')
    ### end Alembic commands ###
